#!/bin/bash

# Author: Robert H Cudmore
# Date: 20180603
#
# Purpose: Bash script to run video-player
#          Be sure to install first with ./install-player

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# abb 20201026, to run from double click
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo -e "Running run from $DIR"
cd "${DIR}"

if [ ! -d "player_env/" ]; then
	echo '==='
	echo "=== error: Did not find virtual environment in player_env"
	echo '==='
fi

if [ -f "player_env/bin/activate" ]; then
	echo '==='
	echo "=== ./player: Activating Python 3 virtual environment with 'source player_env/bin/activate'"
	echo '==='
	source player_env/bin/activate
else
	echo -e "${RED}ERROR${NC}: Python 3 virtual environment not installed in $PWD/player_env"
	echo "Make sure the player is installed with './install-player' and run again with './player'."
	exit 1
fi

python videoapp/player.py

deactivate

echo -e "${GREEN}The video-player just quit.${NC}"

exec /bin/bash
